### ISSUE TITLE
Enhance Frontend Styling

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/Graph-Analyzer#2]
## Description

Currently, the frontend of the application lacks CSS and proper styling, which affects the user experience. We need to enhance the UI by adding appropriate CSS to improve the appearance and make it more user-friendly.

## Tasks

1. Add CSS for layout styling to improve the overall appearance of the homepage.
2. Ensure the styling is responsive across different screen sizes.

## Expected Outcome

The application should have a visually appealing and responsive design with proper styling for all components.

**Comment by haseeb-555** [comment]
I was assigned to this, i will try to improvise the ui

**Comment by VishalMinj** [comment]
I done with the frontend here's the preview, I tried for a clean design since there wasn't much content on to display & the design is mobile responsive. I believe its acceptable so I'll create the pr.
 
![image](https://github.com/user-attachments/assets/580ee242-a653-4e5e-aa0b-085f95b29d1b)
![image](https://github.com/user-attachments/assets/2ff4e27f-f62a-4245-b61e-72b62f46b71f)
![WhatsApp Image 2024-10-17 at 10 55 33 AM (1)](https://github.com/user-attachments/assets/6615036d-9f2b-4a70-a042-208d10822604)
![WhatsApp Image 2024-10-17 at 10 55 33 AM](https://github.com/user-attachments/assets/5c13d4b5-129d-478b-ae7f-1d5167ea5e71)
